package MAP::Model::MAPDb;

use strict;
use base 'Catalyst::Model::DBIC::Schema';


=head1 NAME

MAP::Model::MAPDb - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<MAP>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<MAP::Schema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.65

=head1 AUTHOR

Anthony Okusanya

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
